eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:51666/eureka/
server:
  port: 8110
spring:
  application:
    name: service-paycenter
paycenter:
  secretkey: xxx
  merchantId: xxx
  businessId: xxx
  version:  1.3
  url:  xxx
  method:
    getBankList: xxx
    verifyBankInfo: xxx
    transferMoney: xxxx