eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:51666/eureka/
server:
  port: 8110
spring:
  application:
    name: service-paycenter
paycenter:
  secretKey: xxx
  merchantId: xxx
  businessId: xxx
  feeId: xxx
  version:  1.3
  url:  "https://payment.funpay.asia"
  method:
    getBankList: "/fun/transfer/getBankList"
    verifyBankInfo: "/fun/transfer/verifyBankInfo"
    transferMoney: "/fun/transfer/transferMoney"
    offlinePay: "/fun/payment/offlinePay"
    payCheck: "/fun/payment/check"
    transferCheck: "/fun/transfer/check"