spring:
  profiles:
    active: online
  application:
    name: service-paycenter
server:
  port: 8110

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000


---
spring:
  profiles: test

paycenter:
  payReturnUrl: "https://d45582e9.ngrok.io/payCallBack"
  repayReturnUrl: "https://d45582e9.ngrok.io/repayCallBack"
  secretKey: "2p1opUXzhAsUaX5zaQF451gKvl9303wQGM6542c3"
  merchantId: "1473"
  businessId: "104"
  feeId: "104"
  version:  "1.3"
  url:  "https://sandbox.funpay.asia"
  method:
    getBankList: "/fun/transfer/getBankList"
    verifyBankInfo: "/fun/transfer/verifyBankInfo"
    transferMoney: "/sandbox/customer/getTransferPay.action"
    offlinePay: "/fun/payment/offlinePay"
    payCheck: "/fun/payment/check"
    transferCheck: "/fun/transfer/check"

eureka:
  client:
    serviceUrl:
      #defaultZone: http://192.168.78.32:51666/eureka/
      defaultZone: http://127.0.0.1:51666/eureka/
      #defaultZone: http://140.143.207.211:51666/eureka/

---
spring:
  profiles: online

paycenter:
  payReturnUrl: "https://www.mdongdongvi.online/paycenter/payCallBack"
  repayReturnUrl: "https://www.mdongdongvi.online/paycenter/repayCallBack"
  secretKey: "IIyc8477VSOLtbobbM9nhQiN5Z7HAsga6NWZK4Tw"
  merchantId: "1610"
  businessId: "303"
  feeId: "282"
  version:  "1.3"
  url:  "https://payment.funpay.asia"
  method:
    getBankList: "/fun/transfer/getBankList"
    verifyBankInfo: "/fun/transfer/verifyBankInfo"
    transferMoney: "/fun/transfer/transferMoney"
    offlinePay: "/fun/payment/offlinePay"
    payCheck: "/fun/payment/check"
    transferCheck: "/fun/transfer/check"

eureka:
  client:
    serviceUrl:
      defaultZone: http://172.21.190.226:51666/eureka/

---
spring:
  profiles: online_test

paycenter:
  payReturnUrl: "https://d45582e9.ngrok.io/payCallBack"
  repayReturnUrl: "https://d45582e9.ngrok.io/repayCallBack"
  secretKey: "2p1opUXzhAsUaX5zaQF451gKvl9303wQGM6542c3"
  merchantId: "1473"
  businessId: "104"
  feeId: "104"
  version:  "1.3"
  url:  "https://sandbox.funpay.asia"
  method:
    getBankList: "/fun/transfer/getBankList"
    verifyBankInfo: "/fun/transfer/verifyBankInfo"
    transferMoney: "/sandbox/customer/getTransferPay.action"
    offlinePay: "/fun/payment/offlinePay"
    payCheck: "/fun/payment/check"
    transferCheck: "/fun/transfer/check"

eureka:
  client:
    serviceUrl:
      defaultZone: http://172.21.190.226:51666/eureka/


---
spring:
  profiles: online2
server:
  port: 20082

paycenter:
  payReturnUrl: "https://www.2w.pub/paycenter/payCallBack"
  repayReturnUrl: "https://www.2w.pub/paycenter/repayCallBack"
  secretKey: "pUoZtgB8mtG7mLPmh9RY4XtHJN1e4cN0092IPOPi"
  merchantId: "1758"
  businessId: "506"
  feeId: "486"
  version:  "1.3"
  url:  "https://payment.funpay.asia"
  method:
    getBankList: "/fun/transfer/getBankList"
    verifyBankInfo: "/fun/transfer/verifyBankInfo"
    transferMoney: "/fun/transfer/transferMoney"
    offlinePay: "/fun/payment/offlinePay"
    payCheck: "/fun/payment/check"
    transferCheck: "/fun/transfer/check"

eureka:
  client:
    serviceUrl:
      defaultZone: http://uniloan04:20087/eureka/


---
spring:
  profiles: test2
server:
  port: 20082

paycenter:
  payReturnUrl: "https://www.2w.pub/paycenter/payCallBack"
  repayReturnUrl: "https://www.2w.pub/paycenter/repayCallBack"
  secretKey: "pUoZtgB8mtG7mLPmh9RY4XtHJN1e4cN0092IPOPi"
  merchantId: "1758"
  businessId: "506"
  feeId: "486"
  version:  "1.3"
  url:  "https://sandbox.funpay.asia"
  method:
    getBankList: "/fun/transfer/getBankList"
    verifyBankInfo: "/fun/transfer/verifyBankInfo"
    transferMoney: "/sandbox/customer/getTransferPay.action"
    offlinePay: "/fun/payment/offlinePay"
    payCheck: "/fun/payment/check"
    transferCheck: "/fun/transfer/check"

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:20087/eureka/

