debug: false

spring:
  profiles:
    active: online

server:
  port: 10091
  tomcat:
    max-threads: 4
  connection-timeout: 180000

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false

sms:
  skyline:
    mock: true
    uri: http://sms.skylinelabs.cc:20003/sendsmsV2
    account: cs_wmve6s
    password: 6RWTB71n
    vip-account: cs_3pofo7
    vip-password: hJBJJ7oW

---
spring:
  profiles: test
  datasource:
    dynamic:
      hikari:
        connection-timeout: 3000

      primary: test
      datasource:
        test:
          username: uniloan_test
          password: 13JPTmkZT5QmAV4s
          url: 'jdbc:mysql://140.143.207.211:3306/test?useSSL=false&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&socketTimeout=60000'
          driver-class-name: com.mysql.jdbc.Driver
          hikari:
            max-lifetime: 600000

ontime-delivery:
  redisson:
    host: 127.0.0.1
    port: 6388
    auth: 13JPTmkZT5QmAV4s

rocket:
  consumer:
    endpoint: 127.0.0.1:9976
    group: market
  producer:
    endpoint: 127.0.0.1:9976
    group: market


---
spring:
  profiles: online
  datasource:
    dynamic:
      hikari:
        connection-timeout: 3000

      primary: test
      datasource:
        test:
          username: uniloan_test
          password: 13JPTmkZT5QmAV4s
          url: 'jdbc:mysql://140.143.207.211:3306/test?useSSL=false&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&socketTimeout=60000'
          driver-class-name: com.mysql.jdbc.Driver
          hikari:
            max-lifetime: 600000

ontime-delivery:
  redisson:
    host: 172.21.190.226
    port: 6388
    auth: 13JPTmkZT5QmAV4s

rocket:
  consumer:
    endpoint: 172.21.190.226:9976;172.21.190.225:9976
    group: market
  producer:
    endpoint: 172.21.190.226:9976;172.21.190.225:9976
    group: market
