spring:
  profiles:
    active: test
server:
  port: 8090
  tomcat:
    max-threads: 10
  connection-timeout: 180000
#mybatis:
#  configuration:
#    map-underscore-to-camel-case: false

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false

feign:
  hystrix:
    enabled: false
  client:
    config:
      default:
        connect-timeout: 10000
        read-timeout: 10000

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
  eureka:
    enable: true


---
spring:
  profiles: test
  datasource:
    name: mydb
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://140.143.207.211:3306/test?useSSL=false&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&socketTimeout=60000
    username: uniloan_test
    password: 13JPTmkZT5QmAV4s
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialSize: 1
    maxActive: 100
    minIdle: 20
    maxWait: 30000
    validationQuery: SELECT 1
    testOnBorrow: true
    testOnReturn: true
    testWhileIdle: true
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 25200000
    removeAbandoned: true
    removeAbandonedTimeout: 1800
    logAbandoned: true
    filters: mergeStat
  redis:
    #host: 140.143.207.211
    host: 127.0.0.1
    port: 6388
    password: 13JPTmkZT5QmAV4s

ssdb:
  host: 127.0.0.1
  #host: 47.111.160.160
  port: 13288
  auth: zzzzzzzzzzzzzzzz13JPTmkZT5QmAV4s
  timeout: 300000

eureka:
  client:
    serviceUrl:
      #defaultZone: http://192.168.78.32:51666/eureka/
      defaultZone: http://127.0.0.1:51666/eureka/

---
spring:
  profiles: online
  datasource:
    name: mydb
    type: com.alibaba.druid.pool.DruidDataSource
              url: 'jdbc:mysql://rm-t4n37hf32058pbwmo.mysql.singapore.rds.aliyuncs.com/uniloan?useSSL=false&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&socketTimeout=60000'
    username: dev_online
    password: Dwl12#$%^
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialSize: 1
    maxActive: 100
    minIdle: 20
    maxWait: 30000
    validationQuery: SELECT 1
    testOnBorrow: true
    testOnReturn: true
    testWhileIdle: true
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 25200000
    removeAbandoned: true
    removeAbandonedTimeout: 1800
    logAbandoned: true
    filters: mergeStat
  redis:
    database: 0
    host: 172.21.190.226
    port: 7789
    jedis:
      pool:
        max-active: 8
    timeout: 60000
    password: 13JPTmkZT5QmAV4s

ssdb:
  host: 172.21.190.226
  port: 13288
  auth: zzzzzzzzzzzzzzzz13JPTmkZT5QmAV4s
  timeout: 300000

eureka:
  client:
    serviceUrl:
      defaultZone: http://172.21.190.226:51666/eureka/
