debug:
  true

eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.78.32:51666/eureka/
ribbon:
  eureka:
    enable: true

server:
  port: 10083
  tomcat:
    max-threads: 10

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false

rocket:
  producer:
    endpoint: 140.143.207.211:9976
    group: user_state_group

spring:
  application:
    name: service-core
  datasource:
    dynamic:
      hikari:
        connection-timeout: 3000

      primary: test
      datasource:
        test:
          username: uniloan_test
          password: 13JPTmkZT5QmAV4s
          url: 'jdbc:mysql://140.143.207.211:3306/test?useSSL=false&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&socketTimeout=60000'
          driver-class-name: com.mysql.jdbc.Driver
          hikari:
            max-lifetime: 600000

#        online:
#          username: dev
#          password: Ict123465
#          url: 'jdbc:mysql://47.92.200.47:3306/test_uniloan?useSSL=false&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&socketTimeout=60000'
#          driver-class-name: com.mysql.jdbc.Driver

apply:
  expire-days: 7

loan:
  auto-loan-retry-times: 3

query:
  page-num: 500

