debug: false

spring:
  profiles:
    active: online
  application:
    name: service-core
  messages:
    basename: static/i18n/messages
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
server:
  port: 10083
  tomcat:
    max-threads: 10
  connection-timeout: 180000

feign:
  hystrix:
    enabled: false
  client:
    config:
      default:
        connectTimeout: 20000
        readTimeout: 20000

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
  eureka:
    enable: true

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false

hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE

apply:
  expire-days: 7

loan:
  auto-loan-retry-times: 3

query:
  page-num: 500



#eureka:
#  client:
#    serviceUrl:
#      #defaultZone: http://192.168.78.32:51666/eureka/
#      defaultZone: http://127.0.0.1:51666/eureka/
#      #defaultZone: http://140.143.207.211:51666/eureka/
#
#rocket:
#  producer:
#    endpoint: 127.0.0.1:9976
#    #endpoint: 47.111.160.160:9976
#    #endpoint: 140.143.207.211:9976
#    group: user_state_group



---
spring:
  profiles: test
  redis:
    database: 0
    host: 127.0.0.1
    port: 7789
    jedis:
      pool:
        max-active: 8
    timeout: 60000
    password: 13JPTmkZT5QmAV4s

  datasource:
    dynamic:
      hikari:
        connection-timeout: 3000

      primary: test
      datasource:
        test:
          username: uniloan_test
          password: 13JPTmkZT5QmAV4s
          url: 'jdbc:mysql://140.143.207.211:3306/test?useSSL=false&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&socketTimeout=60000'
          driver-class-name: com.mysql.jdbc.Driver
          hikari:
            max-lifetime: 300000

ssdb:
  host: 127.0.0.1
  port: 13288
  auth: zzzzzzzzzzzzzzzz13JPTmkZT5QmAV4s
  timeout: 300000

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:51666/eureka/

rocket:
  producer:
    endpoint: 127.0.0.1:9976
    group: user_state_group

thirdparty:
  max-retry: 3
  jirong:
    blacklist:
      url: "https://api.geerongcloud.com/credit/v2/blacklist"
    token: testUser
    secretKey: 9437f92c2f774ceb95ea591fc10209e8
    countryCode: 84
  xingtan:
    accessKey: 92d08e368374414bb5848134000460f5
    accessSecret: ABD5691CE596186FE2FDCE8ABE37CBE0996240CE88E580D8EE20F37FC303B14A
    token: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiI5MmQwOGUzNjgzNzQ0MTRiYjU4NDgxMzQwMDA0NjBmNSIsImV4cCI6MTg4MTkyMDg1Niwib3duZXJJZCI6Mn0.bBaUZuNyRygPJxVs5kHUyk-dBPz1P9Gg20rB1VoD7LBNVhuEFNFVExUcI4nDFuGqSl3QOvceAcv3Wm1YFTmoWA
    blacklist:
      url: "http://47.75.14.45/single-pre-rc-report/prc-blacklist"


---
spring:
  profiles: online
  redis:
    database: 0
    host: 172.21.190.226
    port: 7789
    jedis:
      pool:
        max-active: 8
    timeout: 60000
    password: 13JPTmkZT5QmAV4s

  datasource:
    dynamic:
      hikari:
        connection-timeout: 3000

      primary: online
      datasource:
        online:
          username: dev_online
          password: Dwl12#$%^
          url: 'jdbc:mysql://rm-t4n37hf32058pbwmo.mysql.singapore.rds.aliyuncs.com/uniloan?useSSL=false&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&socketTimeout=60000'
          driver-class-name: com.mysql.jdbc.Driver
          hikari:
            max-lifetime: 300000

ssdb:
  host: 172.21.190.226
  port: 13288
  auth: zzzzzzzzzzzzzzzz13JPTmkZT5QmAV4s
  timeout: 300000

eureka:
  client:
    serviceUrl:
      defaultZone: http://172.21.190.226:51666/eureka/

rocket:
  producer:
    endpoint: 172.21.190.226:9976;172.21.190.225:9976
    group: user_state_group

thirdparty:
  max-retry: 3
  jirong:
    blacklist:
      url: "https://api.geerongcloud.com/credit/v2/blacklist"
    token: 735506dbda0040bab7d473f7027cd6fd
    secretKey: 5967f91866e8452eb12dfd07bad43b76
    countryCode: 84
  xingtan:
    accessKey: b7354a93ba194e9c8dbab5b6ef3d62d0
    accessSecret: 2BD2397E05F491DB49FCAD6CE65E76386684C54FCFC98DEFBEBE924EBC5F44A6
    #sha256: a3467f397bcabcbc4f0dea3be1334fef3b368d933cdb631946eca53f332bd5ce
    token: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJiNzM1NGE5M2JhMTk0ZTljOGRiYWI1YjZlZjNkNjJkMCIsImV4cCI6MTg4OTA5MDg3Niwib3duZXJJZCI6MTE5NDU2NzAzNzEzNzk4MTQ0MX0.iX3tKj2DDgLsziTI26tuA8-pkORNjVYEekYUgwFsxVCFxmc-8PnI0-Aj86G6W_G3DB7V8GjRlGZJ_8ovWpXT8g
    blacklist:
      url: "https://rest.star-detector.vn.starwin.tech/single-pre-rc-report/prc-blacklist"


---
spring:
  profiles: online2
  redis:
    database: 0
    host: 172.21.190.225
    port: 7789
    jedis:
      pool:
        max-active: 8
    timeout: 60000
    password: 13JPTmkZT5QmAV4s

  datasource:
    dynamic:
      hikari:
        connection-timeout: 3000

      primary: online2
      datasource:
        online:
          username: dev_online
          password: Dwl12#$%^
          url: 'jdbc:mysql://rm-t4n37hf32058pbwmo.mysql.singapore.rds.aliyuncs.com/uniloan2?useSSL=false&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&socketTimeout=60000'
          driver-class-name: com.mysql.jdbc.Driver
          hikari:
            max-lifetime: 300000

server:
  port: 20084
  tomcat:
    max-threads: 10
  connection-timeout: 180000

ssdb:
  host: 172.21.190.225
  port: 13288
  auth: zzzzzzzzzzzzzzzz13JPTmkZT5QmAV4s
  timeout: 300000

eureka:
  client:
    serviceUrl:
      defaultZone: http://172.21.190.226:20087/eureka/

rocket:
  producer:
    endpoint: uniloan01:9976
    group: user_state_group

thirdparty:
  max-retry: 3
  jirong:
    blacklist:
      url: "https://api.geerongcloud.com/credit/v2/blacklist"
    token: 735506dbda0040bab7d473f7027cd6fd
    secretKey: 5967f91866e8452eb12dfd07bad43b76
    countryCode: 84
  xingtan:
    accessKey: b7354a93ba194e9c8dbab5b6ef3d62d0
    accessSecret: 2BD2397E05F491DB49FCAD6CE65E76386684C54FCFC98DEFBEBE924EBC5F44A6
    #sha256: a3467f397bcabcbc4f0dea3be1334fef3b368d933cdb631946eca53f332bd5ce
    token: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJiNzM1NGE5M2JhMTk0ZTljOGRiYWI1YjZlZjNkNjJkMCIsImV4cCI6MTg4OTA5MDg3Niwib3duZXJJZCI6MTE5NDU2NzAzNzEzNzk4MTQ0MX0.iX3tKj2DDgLsziTI26tuA8-pkORNjVYEekYUgwFsxVCFxmc-8PnI0-Aj86G6W_G3DB7V8GjRlGZJ_8ovWpXT8g
    blacklist:
      url: "https://rest.star-detector.vn.starwin.tech/single-pre-rc-report/prc-blacklist"







