debug: false


server:
  port: 10081
  tomcat:
    max-threads: 10
  connection-timeout: 180000

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false

ssdb:
  host: 140.143.207.211
  port: 13288
  auth: zzzzzzzzzzzzzzzz13JPTmkZT5QmAV4s
  timeout: 300000

eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.78.32:51666/eureka/

rocket:
  consumer:
    endpoint: 140.143.207.211:9976
    group: app_backend
  producer:
    endpoint: 140.143.207.211:9976
    group: app_backend

spring:
  messages:
    basename: static/i18n/messages

  redis:
    database: 0
    host: 140.143.207.211
    port: 6388
    jedis:
      pool:
        max-active: 8
    timeout: 60000
    password: 13JPTmkZT5QmAV4s

  datasource:
    dynamic:
      hikari:
        connection-timeout: 3000

      primary: test
      datasource:
        test:
          username: uniloan_test
          password: 13JPTmkZT5QmAV4s
          url: 'jdbc:mysql://140.143.207.211:3306/test?useSSL=false&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&socketTimeout=60000'
          driver-class-name: com.mysql.jdbc.Driver
          hikari:
            max-lifetime: 600000
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB


