debug: false

upload_path: ./storage

server:
  port: 10081
  tomcat:
    max-threads: 10
  connection-timeout: 180000

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false

sms:
  skyline:
    uri: http://sms.skylinelabs.cc:20003/sendsmsV2
    account: cs_3pofo7
    password: hJBJJ7oW
    vip-account: cs_3pofo7
    vip-password: hJBJJ7oW

ssdb:
  host: localhost
  port: 13288
  timeout: 300000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:51666/eureka/

rocket:
  consumer:
    endpoint: localhost:9976
    group: user_state_group
  producer:
    endpoint: localhost:9976
    group: user_state_group

paycenter:
  uri: http://xxxxx/paycenter/repay

admin:
  uri: http://zzzz

spring:
  messages:
    basename: static/i18n/messages

  redis:
    database: 0
    host: 127.0.0.1
    port: 6388
    jedis:
      pool:
        max-active: 8
    timeout: 60000
    password: dss_worker

  datasource:
    dynamic:
      hikari:
        connection-timeout: 3000

      primary: test
      datasource:
        test:
          username: root
          password: root
          url: 'jdbc:mysql://localhost:3306/test?useSSL=false&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&socketTimeout=60000'
          driver-class-name: com.mysql.jdbc.Driver
          hikari:
            max-lifetime: 600000
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB


