debug: true

upload_path: ./storage

server:
  port: 10081
  tomcat:
    max-threads: 10

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false

sms:
  skyline:
    uri: http://sms.skylinelabs.cc:20003/sendsmsV2
    account: xxxx
    password: yyyy

spring:
  messages:
    basename: static/i18n/messages

  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        max-active: 8
    timeout: 60000

  datasource:
    dynamic:
      hikari:
        connection-timeout: 3000

      primary: test
      datasource:
        test:
          username: root
          password: root
          url: 'jdbc:mysql://localhost:3306/test?useSSL=false&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&socketTimeout=60000'
          driver-class-name: com.mysql.jdbc.Driver
          hikari:
            max-lifetime: 600000

        buyt:
          username: root
          password: root
          url: 'jdbc:mysql://localhost:3306/buyt_new?useSSL=false&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&socketTimeout=60000'
          driver-class-name: com.mysql.jdbc.Driver


